; generated by PrusaSlicer 2.7.4+win64 on 2024-05-05 at 15:20:50 UTC


;
; thumbnail begin 160x120 6652
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAATQklEQVR4Ae2dWW9d1RmGz09oe9+mfw
; Cp0EJDob2q1BaJNh25yWxncGzHCUMCGZ05sTOPnn1sx0PmkARCSAIBGoVAARUpKAKhMEnkKup1blbz
; LGsddo73PvvsYQ17n1PpFW3x2eO7v/VN6/0KM2fOFC5jzpw54ty5c+K7774TnZ2dYuHChVX97pVXXh
; FvvPGGePXVV8WWLVvE/Pnznb3HWkbB5Yt78cUXxZ07d8Tbb78tXnjhBTF37txIv1+wYIEYGRkRb731
; luju7hatra3O3WMtY8mSJe4ScGBgQHz77beiq6tLLF68WMyaNSv2sbCAV69eFSdOnBDr1q2TVtWFe6
; xlbNy4UbzzzjvuEZCv4qOPPhKffPKJWLt2bWpLZ3Nzszhz5oy4dOmS2Ldvn1i0aJG1e6xlsCr19/eL
; zz77TNy/f98tAuLjff3112JiYkISZvbs2aken+NBvnfffVeMjo6KlStXJrKsdVSP5tkzxNm2R8TVkR
; 3i7t27Qv3HCQJi5d58803p723btk1+JTrPh2/52muviQsXLogdO3aIhoYGbeeC4NVC5z3bREfD0+K/
; TYUS7l5ol+RzwgISrX711VcyYl22bJkx/wzS42deu3ZNLgmcO8rvoxArbZh4PmkAqzfY/MRD5APFGQ
; Vx7949cf78ebsEHB8fl+kV5ZPZeLjt7e3i8uXL4vTp02LDhg1TIm2bRMsyKZtn/1W83/rjKeRb87uC
; GNnWLI4cOSLfuRUCLl26VNy6dUvcvHlTWsB58+ZZfVhE2cePH5dEPHjwoAyEskI81wiJ1etb/Etfq7
; ds+oN/dq6QH71a6YwT8MCBA+Kbb74RQ0ND8kWnHWhEQflL27lzp1ySCYJWrVolry0rhHOBkJDvytJp
; vlavZ+U/ZE4W4+P9jTECElgQfd6+fVts2rRJNDY2GjlvGOnKgS+Ib/L6669LQnLdWSCYbTJ2L3g00O
; r1tTfKYM8vpWaEgJhcAg3KYlQjTCeCo74gXAIqJ3wwxWJRVmFcJpRNImL1hlqfDCTf2GCXeOmllwJ/
; r5WALGEkfwk0du3aVXUd1wbp/LB69WqZuObD2bx5s/yCXSWTDTK2zPnblEDj0qyC2P3cNDG0pUm6W2
; HvXBsBn3/+efHll19KK8IXELWOa4t05eABkrSmlEdZsKWlxTnymCYiVq+/6fFAqzfe3SmrWNX491oI
; 2NvbK+u4PT09oqmpKfYXZpN45SBBTlMD0TIPFzfCFdKYJCLku9HyI99AY6xjqcytUsWq9t2lSkDI9s
; EHH4hPP/1UrF+/XmuFwRTxvMD6sRyTNN+7d28pd1krROxZ+Fig1etZN182fURNqaVGQCwEdVw6TnhR
; utIrtl8Ilo9c4XvvvSfTCitWrHCCKDqB1Rtpe2oK+bb/viDW//mnYrj3oHS54rzPxASE8RcvXpTkI9
; TWVcd17aVAPO6blM327dultXftGtPAmvl/FDeX/sTX6g1uWiT27NmTKKWWiIB0k9BAQAVh+fLlWgIN
; l18OD540DQ2z+L1tbW1OX28UUEobWPJE4JJ7cnRAJuv52yTvNzYBWX4INFiOkjaMZpF8XtBceeXKFX
; Hq1CmZ8+RDzMq1B5HvRot/Hffo9haZI8XfT+MdRyYgiWSCjA8//FDmyXTstcjSy1KgrAgBaSsj/6Wi
; /6wRr3dRcB23a81c+bGpD8w4AVnvqeMePXpUS8Noll5WEHhGtJqPjY3JRous1JMh3+XWn/lavZ3zp4
; uBI3t9XQwjBMTXwc/54osvZKito46bhZdULfCHaXal6ZUub9fryd0LfhFo9fo3LJD3UCnI0kpAkq7U
; cXmgdDKkXcd1+cUkAa4JgQnWcHBwUKYpXLtGrF6xZbov+dofpFcmhnpK2xbCkDoBOSg5Peq4LCs6Gk
; ZdeyE6wAeMX3j27FnZBUTayoXrCq7j/lwMb10iDh06FDnRnhoBWUI+//xzcf36dfkFpN0w6sILMAle
; JN3fRMp0AtusJ2P1+pt+5W/1/vIzMdGzU1ax4pYaExOQgjuBBvskdNRxbT14F0CiHl/62LFjYs2aNc
; bryZPpFf867nhnm8xpkuVIep5YBOQrvXHjhmyVZ29E2nVckw/aZeBHIzVCFWX37t2y28bEeXsWBjeM
; 9q5vkKXUNN2DSASk141SGnksHQ2jJh5wlkAe7fDhw7KePDw8LNvVdJ0Lqze89DeBddyj/YflNlUd56
; 6KgNQyowr/1MmXDl5++WXZWYNF3Lp1a+r15NXz/hBYxy1uXiw7enSmiKoiID1ucYR/6uRLBxAAK4hv
; SP8kS3TSY07WcR8PDDROjxelD2oiSR5KwFqv47oC3CC6rk+ePCmj0Lj15EqBxuiOVpmbNL3tNNQHrJ
; PPDXgFlPbv319q8qgWQXVcrF732nmS5DYaJYwR0PSN5RHlAkr4iWFLZaU67q6GJ0Wxe7/M7dq8L+0E
; tHlzeQR+uRJQ6ujokPV3v7/rbPxtYHplYONCuRsx6LcmoZWAtm8uryAqpiCgBJS8VgyrN9j868Al9/
; hIn7SeLt1PnYAZBUEJXecqXbO88TnfOq5X+Ceq/2gCWgjo2k3mFZRFz491i/90NQRbvb7dJeEfV+8j
; VQK6epN5BEtuJeEfcolp5BB1IzUCun6jeUJQHXfDjGmydYqKRlZ25aVCwCzcaB4wWcedKvxz8JnJOu
; 61S+fk/hza/3XVc3UgEQGzcpNZR+vcvz8INB6u45567gfhHxLV1O4pqZUP5HH93uoEdBhhddyxro6S
; 8I/6DURko5h3II/L9xibgC7fVB4QVsdVwj9Bv1cCSmylcF1AKTIBXb2RvKB30WOBgYZX+CfsOEpAiX
; qyywJKdQI6Aqze0WXhwj9RjonlY3M89WSWZhcFlEoEJGNeJ58dBAn/YPUQ/qFlP0kdl05rtK5dFFAq
; EZAIigF+dfKZw2Qd94nAQOPE0f6S8E9SQDr2JVNP7uvrkyLsLjyDEgFpUKQRkn/66by4cLF5QqUBLl
; 7hn7TPy0YzNZDHBQGlEgH5QjDPOK6YatqA6uRLHxAvaIALVu/I6jkPCf/oAMSm41oN5LEpoPRQEML/
; gaOK5Bp7E1BCyNOQFtuoVMdF+Kf/8B6j2oL4lkiGsFneloCSbxRMyE7ozp5VtmjmYWSVbQQNcCHQQP
; iHZlMbwYFXQMnGQJ7ANAwhPElM1ODRNEHPxOSF5QVYvaFWf+Gf9RGFf3SBvCI78WwIKFXMA/IHlHOQ
; 6UDPBMkGF9q6s4Iw4R/8L5cSxNSTSVwjoGRqIE8oAQEXQgaenVqYatdavF3DpPBPcB2XAS5JhH90gg
; +CrhoyIiYElAIJ6PfHRMZYQXJJfL1Z10DWgUp1XAa4pCX8oxtKQAkXTKeAUiQCApxUdlhhCTHVWXiY
; phA0wIVAQwn/ZGnOHO+W/ScUKciI6BBQikxAQLhOhl5p3ZE/NPFAXAVWb6TNjvCPbmD5EKlUA3nSFl
; DyJWDVD765WV4cUTJ+Qy2MrCpHpTquCeEfUyBSJy2HRcSSp5UySkRAQAhPeYd8IRdI6sbkg7GFSgNc
; CDROjQ3K8RV5SuSTAWHCfVoCSoENqXEORkKTTdOqGzfPM3XDBrjYEP4xCXLCuF5JBZRSJSDgCyGjTy
; 0ZU21bhyRtVBrggtVjgAsvpxayA3xgNDTgfsURUAK+BEx6YSw55AlpgMRUU280+WB0IUz4Z7BrX+4+
; uGreNT6uGsgTNT+shYAKfBGoOxHCszchy0tS0AAXAg2Ef6ih1nKFiNJdNQJKXpRnXVInIGAposkVAl
; Lioc3I1kOKg8kBLtkS/rEFfH4aXSlSsGkqbDUwQkAFoiUCExxXLi4L1iKsjou4uIvCP7aBwcEvpGyL
; wQnaQGWUgIC8EYpOVE8w1a5OGA8b4HKsd5fzwj+2QT6YGSgYHD7U8i2kfn0H2gmoQCadXBKmmujJpR
; cZNsAlK8I/rgB/UA3k8eZErRIQUFMkOmanFqba5sgqhUrCP33tjbLcmOfcpi54B/LQQ0BVyDoBAZaP
; LouJiQlpqinv2HhAQQNclPDP6MARrQNkagEEo7R2sT+Z1Y+6uHUCKmD98BPYIEPu0NTIKuA3wAXhH1
; XHVcI/pq4n72DfSbmAknUCAi6ECgKZdZZl/AWd5wsT/jkzMTRF+KeO5IBfLMF01XgFlKwTUIGEJmka
; HFe2AeiYqRsm/EM9u5LwTx3x4V1ysYB0XSsBJScICPhCmFdHPRlTneYO/krCPwxwqVb4p47o8As8+N
; BJy1GkcIaAgKUPf4H6IqYaQiY5HlbvbNsjvg2j1HGHeg4Y3QlWa/AjnwLvGl/bKQIqUD9G3YkvhFxS
; nB38DHAJahiljptU+KeOcFQioBNBSCWwJFJ5oPcMIvLfq/ld2AAXhH+wsq7db95QDfmcJqACkhVKQI
; mid6WW8ErCPwxwIcCp13H1o1ryPURAl0nIUukVUCrf6OMn/HO94QerN7Rzpdw+UN9Oaga5I6CCElCi
; noyPSFUlbICLaeGfWkcU8mWOgICOCzbHQ8J/751ZsY5rS/inVhGVfJkkIGib/09xbt0zvuRjTOl4sd
; vZtq+8Ig75phAwCySs1DDKzjSW5nod1zxyT0A/4R9voHH94jHx8ccf18z+ZJcQl3y+BHSRhGHCP2jb
; ISvGiHt8Q1Qb6hGvGSQhXyYIWC78o6yeGuBCu7+q47L0slON1n9qjfUuZr1ISj6nCTgp/PPUFPJRxy
; XQGOk7JGXjyn9HakYJKJG8Rm7MhfvJG9IgXyABbZMwbIALkmFhwj90XJCuoYwHGWtRQEkX0iKfcwT0
; E/5RSy5W7+ToQKQBLl4BJTWQx+aLywPSJF9FApomYZjwD6pMcedasFmaOjItXhynvskoHtImH6tY6L
; BC3TflJ/zjTa8g/JPGABfqyfiD7NSinlzvA4yGtMlHPZ/trlYJ6Cf8A/nUAJeBI3tT7YymCRLBRa+A
; Un3/h1ny4RaxE5IsBYagqnGtOm6qkvAPA1zohtZVx1UCSuxZpd+wPpBHP/EAG5ForSMwZJtmVUtw2i
; ScFP6ZHhhoHBvuNTLARQkoqYE8WRNQ0o00iccqg6AlHzvBIHtw1L8rRDlQ0psKE/6hgmE6XeIVUKKi
; Um/TT5d8vE/q88i4sROO9Jj33xshoJ/wj9fqTfTstDrAxSugxIOyPULLJtIkH8+R8igfNy4P77f8bw
; pRDxqHfOV1XBVoIPyDL+DKzBEiMyWgpBpeXbguE0iTeHzQ+PBkHOhiR+Ik6G8LcU5Q7U2VC/9467i9
; 7W4OcKGerAbyIKBUCwN50iQfWQtEBvCr1R6eSn9fiHuiSjfkJ/zjreO6PsAFy4dMiG0BJd1Ik3gEdQ
; RyVJ2QWWEXYzW/i03AIBKGCf/gC2RlgIt3II9pASXdSJN8VKgQmiKtxUfL/672t4kI6CWin/CPN9A4
; PV6UsmxZS/ySOOXLRkCJB6xbQClLxON41OYhHSpntMJFPUcqBGyePSMw0ED4B18g68leSncIGOkUUN
; KJNIkHSFfRlUQ1g48T3y/OcRITMEj4B6uH8A+dynnpTsZ18A7kSbNMmBXiAfowyRZg9RCg5GOMe6zY
; BMTqlQv/qEAD4Z9i9/5cDnBRA3nIb9Fdo5YdF5E28SAa+VKyA3Sd444kPWYsAnY0PB1Yx0X4hzRG3v
; fj4mij7kRpKa6AUlaIB1C0pZWN+0UcgIAsjeNGIiBWL0j4hyVXDXDx/saVl6IDuBZUcNRAnmoFlLJC
; OoDF9w4dIiWV5vGrJqCf8I8KNBD+wReg7uf3W1svxRSQ/sA6sAeFQMWk9ddFPICVw8qTlKeRQMnqGi
; UgVq9c+Mdr9YqdK0oDXMKOZeql2ACkwzpQesI/0q2wr4t0CihLkPskEa/KkjrOUwgjX7nwj7J6CP+o
; AS5RT6qbDDYB8Xgu1JNJuqeZ99RBgHJQGiXS50Mi0qehQOf5AgnYveDRQKuH8A/t7V65/biwQRLdwB
; UhR5bWQB6dBPACVwIXAl9PzfbTfc4pBMTqDbU+OYV8DHCBfGODXRW7G+pEnIQayEOETL6MJkwXSQe4
; VrV7kGoPlR9T536IgMENo9PE0Jam0gAX3RflGpmSAOtHgAYJWZqD6uCmXng52J5AvRtrTXc4FSuT5y
; 8RsFz4x7vkjnV1lAa4mLy4vJBRDeRhOeZFK41q08+y/LlyHWzaJ9BQG7RMX4ckIOa3+9mCeL9xqvCP
; GuBi+sLySEjqybT9U0+me4Q8oo1niG9HsYAgg4+C67L1PgvsUrp165a4NrBG7P3Tg+j22Umrh/APfo
; uth5RlQla6XjWQh1QNkWacLEISQLZisShbzNgLk0YgmYiA33//vVD/+d/dO2Jw1b/EcO9Bq19FWrBF
; sjB4B/KQvCbtoftZYEhoDMHikVjGpdJ9zqoIqMh3//59KfCoBri4cHF5h3cgjxJQ0nEeXChayIhwaa
; LQdZ44kAS8d++eXBL4Kl25sFoBlkkN5FECSmkdG0tLKkjtfSZ3a+MeK6Fw+/Zt6QsQjrt2cbUEegvV
; QB7+mdQ3w9ekEoNhIb9n2tesFgUiYF11vjqigXoyA3m8AkpxjkOhgJYpco9KrtiVeyzH/wE+t1k7xW
; /JqAAAAABJRU5ErkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object Shape-Box id:0 copy 0
; stop printing object Shape-Box id:0 copy 0

;TYPE:Custom
M862.3 P "MK3SMMU2S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.13.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
Tx
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 X109.557 Y101.857 W30.8854 H6.2854 ; mesh bed levelling

;go outside print area
G1 Y-3 F1000
G1 Z0.4 F1000
; select extruder
Tc
; purge line
G1 X55 F2000
G1 Z0.3 F1000
M73 P5 R0
M73 Q5 S0
G92 E0
G1 X240 E25 F2200
G1 Y-2 F1000
M73 P19 R0
M73 Q19 S0
G1 X55 E25 F1400
G1 Z0.2 F1000
M73 P41 R0
M73 Q41 S0
G1 X5 E4 F1000

M221 S95
G92 E0

; Don't change E values below. Excessive value can damage the printer.

M907 E538 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0




M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-.8 F2100
M73 P50 R0
M73 Q49 S0
G1 Z.6 F720
M73 Q50 S0
G1 X110.139 Y103.383 F10800
G1 Z.2 F720
M73 P53 R0
M73 Q53 S0
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1075
G1 X111.205 Y102.369 E.04613
G1 X112.5 Y102.046 E.04185
M73 Q54 S0
G1 X137.5 Y102.046 E.78386
G1 X138.917 Y102.439 E.04611
M73 P57 R0
M73 Q58 S0
G1 X139.931 Y103.505 E.04613
M73 P58 R0
G1 X140.254 Y104.8 E.04185
G1 X140.254 Y105.2 E.01254
G1 X139.861 Y106.617 E.04611
G1 X138.795 Y107.631 E.04613
G1 X137.5 Y107.954 E.04185
M73 P59 R0
M73 Q59 S0
G1 X112.5 Y107.954 E.78386
G1 X111.083 Y107.561 E.04611
M73 P63 R0
M73 Q63 S0
G1 X110.069 Y106.495 E.04613
G1 X109.746 Y105.2 E.04185
G1 X109.746 Y104.8 E.01254
G1 X110.123 Y103.44 E.04425
M204 S1000
G1 X110.123 Y103.44 F10800
M73 P64 R0
M73 Q64 S0
G1 X110.497 Y103.552
M204 S800
G1 F1075
G1 X110.515 Y103.493 E.00193
G1 X111.56 Y102.617 E.04275
G1 X112.5 Y102.423 E.03009
G1 X137.5 Y102.423 E.78386
G1 X138.807 Y102.815 E.04278
M73 P68 R0
M73 Q68 S0
G1 X139.683 Y103.86 E.04275
G1 X139.877 Y104.8 E.03009
G1 X139.877 Y105.2 E.01254
M73 Q69 S0
G1 X139.485 Y106.507 E.04278
G1 X138.44 Y107.383 E.04275
M73 P69 R0
G1 X137.5 Y107.577 E.03009
G1 X112.5 Y107.577 E.78386
G1 X111.193 Y107.185 E.04278
M73 P73 R0
M73 Q73 S0
G1 X110.317 Y106.14 E.04275
G1 X110.123 Y105.2 E.03009
G1 X110.123 Y104.8 E.01254
M73 Q74 S0
G1 X110.479 Y103.61 E.03895
M73 P74 R0
M204 S1000
;WIPE_START
G1 F8640
G1 X110.497 Y103.552 E-.01402
G1 X110.515 Y103.493 E-.01424
G1 X111.56 Y102.617 E-.31486
G1 X112.5 Y102.423 E-.22162
G1 X113.519 Y102.423 E-.23526
;WIPE_END
G1 Z.6 F720
; printing object Shape-Box id:0 copy 0
G1 X112.7 Y105 F10800
G1 Z.2 F720
M73 P75 R0
M73 Q75 S0
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.4
G1 F1075
G1 X137.3 Y105 E.73041
M204 S1000
; stop printing object Shape-Box id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
M73 P79 R0
M73 Q79 S0
G1 X133.835 Y105 E-.8
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y210 F7200 ; park
G1 Z49.2 F720 ; Move print head further up
M73 P84 R0
M73 Q84 S0
G1 E2 F5000
M73 P95 R0
M73 Q95 S0
G1 E2 F5500
G1 E2 F6000
G1 E-15 F5800
G1 E-20 F5500
M73 P96 R0
M73 Q96 S0
G1 E10 F3000
G1 E-10 F3100
M73 P97 R0
M73 Q97 S0
G1 E10 F3150
M73 P98 R0
M73 Q98 S0
G1 E-10 F3250
G1 E10 F3300
M73 P99 R0
M73 Q99 S0

M140 S0 ; turn off heatbed
M107 ; turn off fan
M702 C
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
M73 Q100 S0
; objects_info = {"objects":[{"name":"Shape-Box id:0 copy 0","polygon":[[137.500,105.200],[112.500,105.200],[112.500,104.800],[137.500,104.800]]}]}
; filament used [mm] = 64.11
; filament used [cm3] = 0.15
; filament used [g] = 0.19
; filament cost = 0.00
; total filament used [g] = 0.19
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 36s
; estimated printing time (silent mode) = 36s
; estimated first layer printing time (normal mode) = 36s
; estimated first layer printing time (silent mode) = 36s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4 and printer_model!=\"MK3.5MMU3\"";"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and printer_notes!~/.*MINIIS.*/ and printer_model!=\"MK3.5\" and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 20
; cooling_tube_retraction = 40
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y210 F7200 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG1 E2 F5000\nG1 E2 F5500\nG1 E2 F6000\nG1 E-15 F5800\nG1 E-20 F5500\nG1 E10 F3000\nG1 E-10 F3100\nG1 E10 F3150\nG1 E-10 F3250\nG1 E10 F3300\n\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM702 C\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -25
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 200
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 85
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm SPEED @MK3
; printer_model = MK3SMMU2S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+ MMU2S Single
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 0
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.27{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.035{elsif nozzle_diameter[0]==0.5}0.025{elsif nozzle_diameter[0]==0.6}0.02{elsif nozzle_diameter[0]==0.8}0.014{elsif nozzle_diameter[0]==0.25}0.12{elsif nozzle_diameter[0]==0.3}0.08{else}0{endif} ; Filament gcode\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.13.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nTx\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 X{first_layer_print_min[0]} Y{first_layer_print_min[1]} W{(first_layer_print_max[0]) - (first_layer_print_min[0])} H{(first_layer_print_max[1]) - (first_layer_print_min[1])} ; mesh bed levelling\n\n;go outside print area\nG1 Y-3 F1000\nG1 Z0.4 F1000\n; select extruder\nTc\n; purge line\nG1 X55 F2000\nG1 Z0.3 F1000\nG92 E0\nG1 X240 E25 F2200\nG1 Y-2 F1000\nG1 X55 E25 F1400\nG1 Z0.2 F1000\nG1 X5 E4 F1000\n\nM221 S{if layer_height<0.075}100{else}95{endif}\nG92 E0\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.6
; support_tree_top_rate = 30%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 50
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
M84 ; disable motors
