; generated by PrusaSlicer 2.6.1+win64 on 2023-10-06 at 18:13:14 UTC


;
; thumbnail begin 160x120 9780
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAcbklEQVR4Ae2dV5AdRZaGbwzM27C7T7
; A7uy/Lxr4t7EbsvjA7DxMBzLwNmpmYCXW3vEUtqSXhJWEl4SVhhRFyeOGdsBJIQGNlkADhhfDeexs5
; /WVzLtmlqqzKqqyqrG4RcUJ0d917657687j/5MlWR0eHisqhhx6qli1bpi699FI1btw4FXdNknR2dl
; pl0qRJ6vLLL1erVq1S3d3dqdfHSVdXV3AyYsQINWfOHHXdddep008/XY0ZM0b/zpccf/zx6tZbb1UL
; Fy5UEydO9PredUorCUgjR45Up5xyirrmmmvUMcccox98UfCdeOKJ+gGdeeaZavTo0Y0HX5xCJ0yYoB
; fYihUr1NSpUws/oFGjRqnVq1fr95s7d67+OQTglA5AkZkzZ2prdeGFF+ovnwd8WINLLrlEXXHFFerw
; ww/XD6/J4EtTKov31FNP1cBh0eUFDbq/66671DnnnKO9RZ1AqQ2ACAA666yz1LXXXqt6enqcwAfgsK
; JLlizR7nwwAy8qWEB0dsEFFzi7TRY8AJ43b553dx4kAMd3/NEKQh7A7NmztRU744wz9Itt4OPv5557
; rrr66qvVscceq39uKviKKJhQ4/zzz9d6O/roo1OvJ0Ym1mPBzpo1q3aAVAbAtd3/onrH/0LNG/5fVi
; Cyki+66CKtUP4/DjRTpkxRV111lY5bSGjyAC8E8PlU9JFHHqluuOEGtWjRIjV27NjYa04++WR18803
; 6yRm/PjxQQGldADOGX2Qemnmnmpr9x5qedc+VhAS48yfP19bN7IzHpaABiXidkhgiH12g+9nIQQhnq
; a6QCgjv8dKkpwRJ5PwDbZEIxMAkSkj/qgtIUC8ceSvVM/wA60Jx/Tp09XKlSvV8uXLdZCMxbvsssvU
; jBkzdgMvQVi8xHUA7rTTTtNhzZo1a9TixYvV5MmTgwJH5QAUOWPcAW1ruGj4v1sTDgJkyg7btm3T/+
; ZNNOoGX9WKJ0HZvHmzevzxx0upGzYagG1rOLXPGs7qs4aj+q1hFDCsZoJlrB6xDVnbeeedl8v1DiXw
; 4S1uv/12rTu8BtbwuOOO0/oMBRi1A1Bk6cT9NQh7J/xCzR++3wD3S6KxdOnSdjJCEZYEBYWSiIQOvj
; oUzkK98cYbdZ0Qb8HvKFXddNNNut43VJKPzABEukceojb1/KMG4oq+BGXxgtm6tnfSSSfpVRstv1B8
; BZwLFizQP+8GX38CAsguvvhinRFHrR2ZMUkIYcxhhx1WOzCCAaAJllVT/69tDRdMONAKLElKhE8OBX
; x1KBkK7bbbbtOJBnW+pOsAJa5YEpShEBe2soKPcguKWXVytwYhCcqFw/e2gpDyAgE2ZRmKsABgKIEP
; QF155ZW6UgCw0EeW1xHS8DqpLtQBjNoBaIIIt0Hh+YgjjtAPEpc8IEHpONDqYnEpWEIoKd5vKICPOt
; +dd96p47pp06Y5v55EjsVLYnfCCScM2tpgywY+qCBiPXhJguMouC6Z+N+xCUqc4Iah5rCGJDCDGXxQ
; b3xPYuAk1sMFyNdff73OmEny4q7B0vqWqnTVSuJ9zz77bL36cB1cmBjr9VnDdX3WcMdP1nBC5yGJ1/
; I+8MK4F1Y3X3QwAQ/Xecstt2hLj9X39SABMe+JFzrqqKNKAVwdoKQWugsA4W4lbnEppWANd1isoQkM
; PoPyjfDJgwF8sBuAj17HJEuVR0wAEEfDJ9OUCijrAqIPMFKG2r59+0AAwu/iOsjA8hST5445SINwWy
; RBiQMI7w9vjIsXK9tE8PE9SM5IGKDVfMRqtgdPKEThH04Z91wnCPOAkcXJM3/33XfVt99+2w9AVhMK
; pAZFE6Qr8GwumQTFBhZ4Y5RJDYz7aBL4cLMkGoQreIuyQBcVQE58yYPEaJDYNQGILNBHH31UffHFF+
; qHH37Q9G2LmAKrR4IAAIqAz5Qzx/9Gg3Dj5D6X3LGfFTR8LjUyLAmJT+jgQ9ksGEIVivF563VFHzgl
; GkAI+0R9MQQQxgGRBYO+XnvtNfX111+rzz//XLedYXxaMBYgkwfoC3wiU0cN67OGv25bwxmdB1nBQy
; sScSHd19x0iODD0tG9QqaLt3B1QT6AZwrgp9TDc2RTVCggFL0AsnXr1qlPP/1Ufffdd2rnzp3aYxBK
; cE2LleMbeNG4b9kkI0FJsYYkJZR96DUkWQkJfHSCQ6cRIwuPWxfwogKfDMdsPty6Bd77+eefV1999Z
; WO9+69916dSLFoBKCtssEngjXc3Mcn7/iJT7YBCutHVgkI+ZebrRN8hAg8XDJ3KYOEAjxTWBTSk0ko
; Uxfw6GtkoX7wwQcaeCQc5Bj8PpqkVQbAqDW8Z8JeVpeMSMMrSQrKrQN80jBKWJCnYbTqh88Dhjkhnq
; bUIdamKuGzt2zZor788kudaGzcuFE3p0jZKKof7wDM4jLnjjm4Xa5ZPHxf67UokNoaCsX6cNNVgA9l
; YUmgEOHBs/K4dQEvzgoRFzJggLi17M/jOaGrN998U33zzTfqk08+0cktNCSLwry2NABmAZ/pkl0SFF
; qYKBMR/LuCwVVQ2h133KGDe6xwk4BnCnqiaC17d6JA8CXEn/fff7/Obr///nv1wgsvaKNhi0VrB2Ce
; BIUvJDxrHoI/iwA6rC1Fclcet2xA5RWydRgUdEch2Od70wG/Y8cOXV5B2EhP00pabdI7APOAL8kaTu
; wclngtN89qxr0IY+MDeDwYalNk4KxoU0lNBp8Ii0m20wKQou9HDZLY+OOPP9blFVwv708VI6ul9QbA
; IuBzsYbmA0cBxDe45aLDegicZfCPK49bJYh8CLVCumtwkXn5ZLzDU089pcsruNyHHnpI06l5Ep6gAB
; hNUC4avk8s+EQw82R6uGS6jl2Bx0qFScg7+Kcq0PgWGaBEdYEYN+vrCIGIJ9955x1dXvnoo480G4Qx
; yBtfFgagT/AlueSZXQdbgSANr9TpssZtxEXSMJqn67hKwJQhAIbFywKk1poWs8FSPfzww20e9+mnn9
; bDByiPFUluCgGwDPCZstDgkxd07G8FBIqABRA+2XYtsYoUufPwuFWDpUwhmcODEPvG8cmAi474V199
; VScZAJBwBR37aIIIGoDItNF/UvdOy2YN+UK4UtwCNFC0XENtjM1BdBeHwOOGIixCsln0JqNB+D3u+Z
; 577mnzuICQ63Dhvko6uQFYBfjMB79s0v+0E5Q0awjQWLVkyvDJ/A53U3TwT0igKUOotaIjQAbz89xz
; z+lEA/Bt2LBBs0K+mZXGABA5duzvNZ9MggKfbAML1o8YBXdx33336Yy5yOCfOoFRpeAZtm7dqhMMEo
; 33339f06Es5DIK2bkAWAf4REyXvGbsXlaXDHXHyqVKTyF2t+WzC6WUTZs2tXlcanvQkdJEUMZnNg6A
; pjVs88kd++4CGNkUT9EaBZKg0KEhfPJuAP4suFWs3BtvvKF5XGI+FiwulwSFZlIsYBAADAF8cdZQEh
; R2WjH4J8rj8mWl4ZUYJ2v2WwcgqhSy2fXr16vPPvtMF5Vfeukl3Z2Ot8DqoSd+lkm3vi1howEYl6Bc
; P+9vOvZLqgfCmrDFkfpXGp8cAkDKFBYpgKO8guUj48VDxCUaABWryNYNnw2vwQEwT4xGDfD2q5eqp4
; /aWwNxddev1KSuYYnXs4rpUWNVyyTXoQRA2rNIzj788EOd4b799tu6iE8d0Gbh0LMMUBK+vFIAhmj9
; cAvU9qj7Yd1Mazin8wC7C++zgNJBHOWAqwZFVcIuOnajkWjgctmlBheOx8jqXtE5fDIlraL7k4MCoA
; vwuHnqfATPEpvEJSjwybb3QYEoEgYltE09PgXrRaH5rbfe0u6WLhY8ADFzHkZDBijJgTylAzAk68eG
; bDnAJek0IklQnu3ZIxODQosSlhCaru6pA76FuK63t1fTaFi9Z555pl2QL5JUyPQzOZAnD5AbB0BoNN
; mQnSWTdWFQeCAE2VhDoeqaLIALjpetkCQauF0qBMRvPhkNqg24ZDmQp5EATAOSOfjH9QAXFz6Zh0ZB
; FvdOf2AoUwdchfgWL8HeDBKN119/XS9el4ZRF5EBSrhllwFKrRDAlwZArB3gY19ukRnKWayhKIZMUa
; YfUMguCyhlCG4RNys87gMPPKCbNKrYIScDlEgKiTsbDUAZ/AOPS1WeG84LviwJSlQ5PDA5MZRMseyH
; V1SwbjAXMviHfbnEtSymKi25DFCSA3mCB2AcUIhT2JkGhSYdLb4kKUFJUhLxIMpkc3WWVV2HYOE4c0
; R4XBoKGGBUtGE0r/CZeC4WL/eRtABaACA0AGLxoMwks/IJPlMWTvj/dsMrfLJNoTxIWpQItn1s6vEl
; 6IeFweAfyitQanDezGQJIX6VAUq0x8WFMi0UapuKVaX7lcE/cLUosCzgJVvDvdSsrt9bFUooQFxICa
; jqqQNRwTIzb0V4XBn847Nh1IegJ+5LBiiZ99aSHWFyKnpdACTBiB7gUqUsn2wkKJ37WxUKZUW9kPoX
; K7yOh4o1ZgO4DP5hApU5+CdEIawiQRkwHQsAsJJwe5jy6GTUssGHwgBe0gEuVQmfO330n38eoDTin9
; XkEX9KVCbujT0lgJAYpyqLQzxM13LS4J8qAZVHMC7crwxQaich/AHrgwuksFgFAHFnWQ5wqQqAImIN
; 1078h1SXjK7kCFbfUweiwjDMJ554InbwTxPAZ4qcOzMgC+ZBUEQkxgEU/FwG8LgB2ZdK0TeEMzCiCj
; pu3B8GlGtsygQAMkCJUMb3w+L90Zc5+EfayZpaKEcwOrFlGMw5QTauEV/tE3zm4J8kHjcEACK4ZJcE
; RQYowQj44pPJuCkky+AfBj7K4J+mWb04SawDCiVFSi+nohcVQCcHuBD7SQISKgBFXBIU3DBDgLCGRa
; bYo3/e5+WXX9Y8LskGG+kBZMiJhjcASvyHEmWojYDGVVitMvhHToI0M+DQAYhEraEtQQE8LFrancju
; Xd2kbCswB/+gu7J43KABiOBOqGqjFADkAj6CZDnAJc6dNwWAIi7WkBINGR+LN+sUe6g/xl6Yg3/odx
; xsLWJOABSgSM8croEXpyUauFs5wCXp+qYBEHFJUPAaMkBJEq6463DdlHRk8A/t8gAXEDc50fAGQBHc
; AJ0OWDWSlbhrqO+YB7jYgNpEACKuCQqeg8VLh02UT2aBPvLII+3BP4w+8zH4J3RB784ARFAKlIpMEu
; WN5G/Ei1Au1KyyHM0aCgDzgBBZNOG3Pw9QSnHJhCAkYtCfsALoh81A5uAfFravwT+hgy83AEUIlik5
; AES4Wyg93LPwuFlixKYDEHGxhlJdIJ6mkCyDf1555RXdjR0ajxs0ABHcBEVRGiCJ91zrhoMBgCJZEx
; Q6rZmrLIkGc/fKGPwTOvgKA1AaRuFxmddM0MwuKZdT0UMCoA8QkqDAJ2MN4ZPNv5EJU9xn4A+Jxnvv
; vactIZ5D9ieHCJiywFcIgFB28MbC4/I73Aerm9/DeAxFAIrcMOU/B/DJ1AU3b97c5nH5f5oZ8CA0g0
; BLIqEcs1UF+HIBkBcJ+S5nT0TLL/ChFGEBIz8PRQAiZrnm/oV/bQ/+IQmhicFMNAAi1QX+Vuep6FWC
; zxmA1KRk8E+ahaP8QmNpFj55sIKQ0kvvHavVa+f8Trvk+3r+TS05sdvK49LTRyhDMjdYis82XWcGIK
; 6W1UnZJSslxwrHSlJaoJrPBzYBgD5ASEYrg3+QjUtGZWZQZIASxWuXKfZNA18mALIKaUiQA1ySQGQT
; yjLUuyjExoF3MAEQy0+PIxNGKa8wCoMkDVD1jPlLO0FJ45NZvDJACSaliXXBLHq2AhCrRYaWxOO6CD
; EO1hMXTtAdOgDzgJAunyeffLI9+Ad2Aw8QdaUufLIMUJIDeUIBV1HgWQHIH1h51PVkYE8R8JkJCgE2
; MQ4uykxgmgxCGfzDmDMSDawfbJDtABfXhlcZoMT2y1CAVhR8XL8LAGm/ysrj5hU4ZDbV0KIlJZxQAZ
; gGQpIGOlZk8M/27dvbG6vSHpYrn0wIRBiDSw9xf7KLTgnFCDEGAJDZIXKACzFHVjYkj/D+uHh2SdHq
; FTIA40CIZYP3hkKTwT/EfmS+rvGauOQsfDK1VrwHCWEoA5Rc9YhhI6llI5wGIF+KTJXUX+IzFzquiJ
; DlkeDQiuR6PGpdIIwO/mFTuByFmpfNcOWTWbwhDFBy0R/3CeWIBcfDoscW1ocsFyotboN62QBE+Fys
; LgkK+ypCBmF08A9HQBAn++JxXRIUGaAkB/KECjyExYnuyCtIzGQHYYvyCHEMFxVpSigqfD4xDiwLK6
; TsU9FdhQyUJAD+Vg5wgQ0q4wAXM0GJ8slRAfhUF2gIIaYqm0921Rv3Q3sZ4R21TUIUc65jiyTAVoqp
; CoAiPGjKPsRTeU6xLEOig3/Ym4vnKJOpcE1QZIASJZsy+OQ8epOtHNwTi0SGoJvXBDOezbSE3CSxAq
; sas51XAUUFK4zyGO4og3+gFqkUSNzFdWWBEJGG1/4Def7Dei2ZMcE9iZ2vAUp59Mbr6BWFsiXRoPSW
; FN8HNaLXBCGCBcR0FzlmK69gUThjTgb/0L9H6UisS5LiQ7CGciAP2XLe2LTIoiVBIrSjuUJqoUnXBw
; lAE4RSL8IlE+xXAb7o4J+1a9fqVWxavTQLUIa4DlCiuoAXyTrFvojO5DMJn0g0AKFtsTYGgCIEsphz
; jmXIc8h0FqFATnGcHWkAjx1qZJlxsUvWh1KGNTQbXtP4ZPbmUOIiBotLUHzojffF5ZNkyGi9rElkcA
; fV2EDIioJloFzje35gdPDPY489psfyigsr+v5lWUMaXud2/cZ6LfU2Fm7cgTxFhbiTbm5iZUppwldn
; fX3QAIwDIV+OshHcK8XMooONZPCPeYALFgO3VfbQpKIgzMInm9+TKQ2UknzM2+b1JGNYPMpmWMA8RE
; KQhxXaAChC/Y0siyI6qy6PElHagw8+2OZxn332WZ11C8/qA2RlgzPPgTwsOOLDvMwTXgHvQEgEqKUW
; mue9ggegDYTEGTJAiUTF5eGSXZuDf2TsSGgF8KziciAPbhjLJQOUXPQG2Mhu5eSCoos12AOrs4IQkQ
; FKUFJpq5qyAOPhZPAPhzQTPAs1lFeRIUjUGqadGAolhs6wYmkWjL8T+qBnOYvZx2JtDADTQMhKlAFK
; 0rkdFRIY2qWEx8X9mge4lAGKOsTFGsIny6kESVNqSf7oFSDRwNP4XKy5ABgqCCXGIdvDqskKRYEkFt
; EDXIrELqGLy4mh5oE8hDQCLv6lIE+nj4zW810CaxwA00CIsJKJU9hOgFXkTFwZ/EPLPK3zwuOWCYK6
; xSVBQai10gxC7ZOaKKUpisp4DhmC7vsecwMwdBBi9WBPsHYkGoy4pchM/XCwWr0k6T+Q55dq4+Q9Mi
; UoxHkbNmzQu/Kg9crs0ywEwFBBSFICfSaDf3C9DAKiIDvYrV6S9FvDf+2zhntqPjnOGhKyADjqeoQo
; LGCqBWVWBhoNwDgQ0iHMIG/hcTlJCF4St0uCgoKreOChSn+C8stdEhRqqdRASUiIA/EgxMhYQ7ZpkK
; yUcT+FARgKCFFgdPAP8YuMxuUagmgyOX7f1HqfD8Eabu75J20NV/bxyVQNSNpINmQ2oVxLuCIH8vCv
; bw/iBYB1gzA6+EcOcInL2KQ1XA7kqRMIdcvKKf+rreGD0/dWi44ZZ+Vx0RV8sgxQKvrZ8uy8AbAOEL
; JSUQjFZDnAhcA5LdZjVcsAJbLloRYXSoMC/YLXnX2kBuG27j31iaG215kH8tCeVgR4jQcg7pRMTQ5w
; oX8P5bgcdCgDlKDyfHeJhCpCX1JqQV/ogJEhaQmKKXIgDy47a10w6Tl6BWAVIOTLsHLpUJbBP2ykJ4
; 6R8op5bZqgQFw4JRr+rRMcZQu1PJI0Eg2ae6OLNSlBiRM5kEc8jivwSgNgmSAkKzMH/8gBLkIN2UCb
; JjJAiZVdVsNrXcLCxGWiKxav7GmJuzZarrHxyeicrhj4ZIrVZiiT9ZmWAsAyQAijYQ7+kQNcRJFZra
; dNCK5lgBLZYN3A8SHSxOvK47pYQzmQh8XL+7s819IA6AuEBL6sMBn8Iwe4ELvYrF5eIPKeZozTVNaE
; 74FVJ8allkeI4mrZ+/nk/gTFxiejUwyBHMhDg4f8vlYAFgUhboMJ8tIwyhFWWCihhoqC26Z86odsTp
; IDeeoAUV6RjVzEenSxcP95M31xyQDRTFCS9InnYH8ybEqWQaalAzAPCPki5uAfAEhjAZ0Z0ZnUviRO
; +axqVjODgGBSmlCuMQf/0L/ni8c1+eT5HftZdUlyw3YJyjXRWZC7AJDVERIIyajuvvvu9uAfThEicJ
; aMrQzwpQGRIixMAe1KLmWeKkU282N5sNy+9rSYupk6aphaN/XX7QRlRudBVj2SabN3h8w7yXC0pD0p
; BBDCULAvQxpG169frwvGZVk9FzCaA5TyFmHLkujgn6JMRZpezAQlzRpi4FgUADHubMHWdz91i8AKsL
; rrACIKjA7+gfaRDt06wJcESIJ57o2STd18MiGBDP5BojyuL8DFydwxB2s+mQRlRdc+1msxIFQx4JNl
; 704bgFgcQIjVoXGTuKFKEBJjwd0Kj7tly5bMBx3WJSwY9lFQk8TV1QE+c/APHizrflyfehCXjDVcM9
; bukhHqj1Cn3DP3rwGIi4NJINDH+hD4YzJBbZkA1Jur+1yGDP6RA1yExw0FbLZVLQOUAKPccxXgA/QE
; +dBplIziyitV6gJr2OaTh+9rvZZ7JSbE4+FNWvwShgHQAQasEAN5aOjki5YBPupT5uAfztPgpnyVV6
; oUirDUC2WAUpbX5AWeOfgHfZHx1hUfR8W0hmkJCkIcTa211dHRoUEBMgmye3t7tTvGKjEJlNXNC3yB
; jwztxRdfbH8GGa+MEgtBkXlENmpTKnIpwmYV3k8G/1Be4TOqqgq4ikuCQiijASjCF8JPk7HAOGCd+J
; fVzcVFgIcCKerK4B+YDayudKEkJShNEb4DNS/cInFO1tOk0kR2+lEGMnncur5nFsEaSsMrCcrEzmGJ
; 1w4AoFhDXAmrbdu2bRosWKtNmzZp858HfGQ+W7duHXCACy1B4j6SEpQmCrpji6MMUCryXnK4D7EyiZ
; ks1jq/n4uY1nB2xwHZACgiKw+rRc8dQKTxU8ajZQEeK9Uc/CMHuMj+grTXN0HJcYLu5EAepgi4hhfo
; huI3Fs/kcUP7nlnETFDgkzMDEOECiofUmHbu3KmtF9kyk+FxNzbwoDRz8A/xJGS1KNLFgjZF2VFBd2
; Sr9BpSJsnyGjngEVdOcVl43BC/X1bRCcq0vgTlsIEJCs/WCkBxyaIUmAncKNaMDmSUG7VkvLEAVg5w
; Yf+FHKpSJI5sktJNQBG6sGEKN5rkQvm9OfjH3I/blO+aJtol94Hw1EP2aT/TVACa1pCyDAE2zAlWDb
; 6WYqxM2se1MvhHeFzKOrQDEcsI4n1Ik5QuIgfyyAAl828y8xB3Kwe4hFJe8SXy7Eb+7ZABzzIzAMUa
; AiZcKUkJlhArR4JBC445+Ac3LTyuL+A1HYjCJ+MRCFH4HfqkZSrK4zbpe6WBziZOADTLNfCOMBckKB
; SvRUg0sJLC45YFvqYCEZ0APhYseqKIbfK4TfouRYBXCIDikikRMOQRd8x/P/74o7aCxDyuNzKUwAjQ
; sHpMbWBrgUykasK9+wCdFwsIHcQhfdIwCp0m4zAAJYXTsvnkpgERvUnDKFku/XI0FNDGTljTJNfr6z
; n9HbB0jLqXTdNTAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
M862.3 P "MK3SMMU2S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.13.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
Tx
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

;go outside print area
G1 Y-3 F1000
G1 Z0.4 F1000
; select extruder
Tc
; purge line
G1 X55 F2000
G1 Z0.3 F1000
G92 E0
M73 P5 R0
M73 Q4 S0
G1 X240 E25 F2200
M73 Q5 S0
G1 Y-2 F1000
M73 P18 R0
M73 Q17 S0
G1 X55 E25 F1400
M73 Q18 S0
G1 Z0.2 F1000
M73 P38 R0
M73 Q38 S0
G1 X5 E4 F1000

M221 S95
G92 E0

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0

M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-.8 F2100
M73 P46 R0
M73 Q45 S0
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.2
G1 X115.936 Y86.266 F10800
M73 Q46 S0
G1 Z.2 F720
M73 P48 R0
M73 Q49 S0
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
M73 P49 R0
G1 F1200
G1 X117.002 Y85.253 E.04611
G1 X118.298 Y84.929 E.04189
G1 X118.678 Y84.929 E.01191
G1 X120.095 Y85.322 E.04611
G1 X121.108 Y86.388 E.04611
G1 X121.432 Y87.683 E.04186
M73 Q50 S0
G1 X121.432 Y127.483 E1.2479
M73 P50 R0
G1 X121.039 Y128.901 E.04614
M73 P55 R0
M73 Q55 S0
G1 X119.973 Y129.914 E.04611
G1 X118.678 Y130.237 E.04185
G1 X118.298 Y130.237 E.01191
G1 X116.88 Y129.845 E.04613
G1 X115.867 Y128.778 E.04613
M73 Q56 S0
G1 X115.544 Y127.483 E.04185
M73 P56 R0
G1 X115.544 Y87.683 E1.2479
G1 X115.92 Y86.324 E.04421
M204 S1000
M73 P61 R0
M73 Q61 S0
G1 X116.294 Y86.436 F10800
M204 S800
G1 F1200
G1 X116.312 Y86.376 E.00196
G1 X117.358 Y85.5 E.04278
G1 X118.298 Y85.306 E.03009
M73 Q62 S0
G1 X118.678 Y85.306 E.01191
M73 P62 R0
G1 X119.985 Y85.698 E.04278
G1 X120.861 Y86.743 E.04275
G1 X121.055 Y87.683 E.03009
G1 X121.055 Y127.483 E1.2479
G1 X120.663 Y128.79 E.04278
M73 P67 R0
M73 Q67 S0
G1 X119.618 Y129.667 E.04277
G1 X118.678 Y129.86 E.03009
M73 Q68 S0
G1 X118.298 Y129.86 E.01191
M73 P68 R0
G1 X116.991 Y129.469 E.04277
G1 X116.114 Y128.423 E.0428
G1 X115.921 Y127.483 E.03009
G1 X115.921 Y87.683 E1.2479
G1 X116.277 Y86.493 E.03895
M204 S1000
; printing object zzz.obj_10 id:0 copy 0
;WIPE_START
M73 P73 R0
M73 Q73 S0
G1 F8640
G1 X116.312 Y86.376 E-.0282
G1 X117.358 Y85.5 E-.31504
G1 X118.298 Y85.306 E-.22162
M73 P74 R0
M73 Q74 S0
G1 X118.678 Y85.306 E-.08774
G1 X119.289 Y85.489 E-.1474
;WIPE_END
G1 Z.6 F720
G1 X118.488 Y127.293 F10800
G1 Z.2 F720
M73 P75 R0
M73 Q75 S0
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.38292
G1 F1200
G1 X118.488 Y87.873 E1.11445
M204 S1000
; stop printing object zzz.obj_10 id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
M73 P80 R0
M73 Q81 S0
G1 X118.488 Y91.338 E-.8
;WIPE_END
G1 Z.6 F720
M107
;TYPE:Custom
; Filament-specific end gcode
M73 P81 R0
G1 Z1.2 F720 ; Move print head up
G1 X0 Y210 F7200 ; park
G1 Z49.2 F720 ; Move print head further up
M73 P85 R0
M73 Q85 S0
G1 E2 F5000
M73 P95 R0
M73 Q95 S0
G1 E2 F5500
G1 E2 F6000
G1 E-15 F5800
M73 Q96 S0
G1 E-20 F5500
M73 P96 R0
G1 E10 F3000
M73 P97 R0
M73 Q97 S0
G1 E-10 F3100
G1 E10 F3150
M73 P98 R0
M73 Q98 S0
G1 E-10 F3250
G1 E10 F3300

M140 S0 ; turn off heatbed
M107 ; turn off fan
M702 C
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 66.35
; filament used [cm3] = 0.16
; filament used [g] = 0.20
; filament cost = 0.01
; total filament used [g] = 0.20
; total filament cost = 0.01
; estimated printing time (normal mode) = 39s
; estimated printing time (silent mode) = 39s
; estimated first layer printing time (normal mode) = 39s
; estimated first layer printing time (silent mode) = 39s

; prusaslicer_config = begin
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and printer_notes!~/.*MINIIS.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 20
; cooling_tube_retraction = 40
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y210 F7200 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG1 E2 F5000\nG1 E2 F5500\nG1 E2 F6000\nG1 E-15 F5800\nG1 E-20 F5500\nG1 E10 F3000\nG1 E-10 F3100\nG1 E10 F3150\nG1 E-10 F3250\nG1 E10 F3300\n\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM702 C\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -25
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 85
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3SMMU2S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+ MMU2S Single
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 0
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n\n{if printer_notes=~/.*PRINTER_MODEL_MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.3{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.13.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nTx\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n\n;go outside print area\nG1 Y-3 F1000\nG1 Z0.4 F1000\n; select extruder\nTc\n; purge line\nG1 X55 F2000\nG1 Z0.3 F1000\nG92 E0\nG1 X240 E25 F2200\nG1 Y-2 F1000\nG1 X55 E25 F1400\nG1 Z0.2 F1000\nG1 X5 E4 F1000\n\nM221 S{if layer_height<0.075}100{else}95{endif}\nG92 E0\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.6
; support_tree_top_rate = 30%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
